baseURL = 'https://example.org'
languageCode = 'en-us'
title = 'Aquib Shaikh'
theme = 'ananke'

[[menu.main]]
  name = "About Me"
  url = "/about-me/"
  weight = 1

[markup]
  [markup.goldmark.renderer]
    unsafe=true
      